name: wppd-plugin-dev

services:
    wordpress:
        image: wordpress:latest
        restart: unless-stopped
        environment:
            WORDPRESS_DB_HOST: db
        volumes:
            - ../plugin:/var/www/html/wp-content/plugins/rumble-wppd:ro
            - wordpress-data:/var/www/html/wp-content
        depends_on:
            - db

    db:
        image: mysql:5.7
        restart: unless-stopped
        volumes:
            - db-data:/var/lib/mysql
volumes:
    db-data:
    wordpress-data:
