name: Build & Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    outputs:
      version: ${{ steps.get_version.outputs.VERSION }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.4"

      - name: Install Composer dependencies
        run: composer install --no-progress --no-suggest

      - name: Get version from composer.json
        id: get_version
        run: |
          VERSION=$(php -r 'echo json_decode(file_get_contents("composer.json"))->version;')
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "::set-output name=VERSION::$VERSION"

      - name: Build plugin zip
        run: composer build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: rumble-wppd
          path: rumble-wppd.*.zip

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: rumble-wppd
          path: .

      - name: Create release draft
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: v${{ needs.build.outputs.version }}
          release_name: v${{ needs.build.outputs.version }}
          draft: true
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: rumble-wppd.${{ needs.build.outputs.version }}.zip
          asset_name: rumble-wppd.${{ needs.build.outputs.version }}.zip
          asset_content_type: application/zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}